// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String apiKey = dotenv.env['ApiKey'] ?? '';

  static FirebaseOptions web = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:790743877683:web:ad9630ef08c9f2e0877b46',
    messagingSenderId: '790743877683',
    projectId: 'circle-b3f90',
    authDomain: 'circle-b3f90.firebaseapp.com',
    storageBucket: 'circle-b3f90.firebasestorage.app',
    measurementId: 'G-WDGP8D7970',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:790743877683:android:7f6296c910cdbf9e877b46',
    messagingSenderId: '790743877683',
    projectId: 'circle-b3f90',
    storageBucket: 'circle-b3f90.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:790743877683:ios:f46c72f4c0804e49877b46',
    messagingSenderId: '790743877683',
    projectId: 'circle-b3f90',
    storageBucket: 'circle-b3f90.firebasestorage.app',
    androidClientId:
        '790743877683-eul17b8eu86ps0k9ljhe4p87ulr19sqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:790743877683:ios:f46c72f4c0804e49877b46',
    messagingSenderId: '790743877683',
    projectId: 'circle-b3f90',
    storageBucket: 'circle-b3f90.firebasestorage.app',
    androidClientId:
        '790743877683-eul17b8eu86ps0k9ljhe4p87ulr19sqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:790743877683:web:1c270e87f3bf197b877b46',
    messagingSenderId: '790743877683',
    projectId: 'circle-b3f90',
    authDomain: 'circle-b3f90.firebaseapp.com',
    storageBucket: 'circle-b3f90.firebasestorage.app',
    measurementId: 'G-KM249X1GRZ',
  );
}
